paths:
  gpt: "//www.googletagservices.com/tag/js/gpt"
  jplugs: "jquery-plugins"
  jquery: "jquery/jquery"
  flamsteed: "flamsteed/lib/javascripts/flamsteed"
  sailthru: "sailthru/v1"
  s_code: "omniture/s_code"
  trackjs: "trackjs/trackjs"

modules:
  - name: 'app_core'
  - name: 'app_core_legacy'
  - name: 'app_secure_core'
  - name: 'app_secure_core_legacy'
  - name: 'styleguide'

findNestedDependencies: true
